version: '3'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: denuncia
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"

volumes:
  db_data: